name: Build and publish .NET app

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x' # match the TargetFramework in your project (net9.0)

      - name: Restore
        run: dotnet restore .github/workflows/MyApp.csproj

      - name: Build
        run: dotnet build .github/workflows/MyApp.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish .github/workflows/MyApp.csproj -c Release -o "${{ github.workspace }}/artifacts/myapp" --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ${{ github.workspace }}/artifacts/myapp
